# Generated by Django 5.2.5 on 2025-08-28 18:09

import uuid
from django.db import migrations, models
import django.db.models.deletion
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # 1) Habilitar extensión trigram ANTES de índices GIN
        TrigramExtension(),

        # 2) Modelos
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('tipo_doc', models.CharField(max_length=12, choices=[('CI', 'CI'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')])),
                ('nro_doc', models.CharField(max_length=32)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120, blank=True, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=32, blank=True, null=True)),
                ('email', models.EmailField(max_length=120, blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=40, blank=True, null=True)),
                ('es_tutor_legal', models.BooleanField(default=False)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_como_apoderado', to='passenger.passenger')),
                ('menor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_como_menor', to='passenger.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='apoderados',
            field=models.ManyToManyField(to='passenger.passenger', through='passenger.PassengerRelation', related_name='menores', blank=True),
        ),
        migrations.AddConstraint(
            model_name='passengerrelation',
            constraint=models.UniqueConstraint(fields=('menor', 'apoderado', 'vigente_hasta'), name='uq_relacion_periodo'),
        ),

        # 3) Índices
        migrations.AddIndex(
            model_name='passenger',
            index=models.Index(fields=['telefono'], name='passenger_p_telefon_b5d7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='passenger',
            index=models.Index(fields=['tipo_doc', 'nro_doc'], name='passenger_p_tipo_do_700571_idx'),
        ),
        migrations.AddIndex(
            model_name='passenger',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['nombres'],
                name='ix_passenger_nombres_trgm',
                opclasses=['gin_trgm_ops'],   # 👈 clave
            ),
        ),
        migrations.AddIndex(
            model_name='passenger',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['apellidos'],
                name='ix_passenger_apellidos_trgm',
                opclasses=['gin_trgm_ops'],   # 👈 clave
            ),
        ),
        migrations.AlterUniqueTogether(
            name='passenger',
            unique_together={('tipo_doc', 'nro_doc')},
        ),
    ]
