# Generated by Django 5.2.5 on 2025-08-28 18:13

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_enable_trigram'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passenger',
            name='ix_passenger_nombres_trgm',
        ),
        migrations.RemoveIndex(
            model_name='passenger',
            name='ix_passenger_apellidos_trgm',
        ),
        migrations.AddIndex(
            model_name='passenger',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nombres'], name='ix_passenger_nombres_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='passenger',
            index=django.contrib.postgres.indexes.GinIndex(fields=['apellidos'], name='ix_passenger_apellidos_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
