# Generated by Django 5.2.5 on 2025-08-23 20:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_office'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0007_alter_driverlicense_back_image_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_entity_08ba2d_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_created_606b86_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_role_1fa9a5_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VEND', 'Vendedor'), ('CAJE', 'Cajero')], db_index=True, default='VEND', max_length=5),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['entity', 'record_id'], name='audit_entity_record_btree'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='audit_created_brin'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['user', 'created_at'], name='audit_user_created_btree'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['action', 'created_at'], name='audit_action_created_btree'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extra'], name='audit_extra_gin'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['role', 'office'], name='user_role_office_btree'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['must_change_password', 'is_active'], name='user_pwdflag_active_btree'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['last_password_change'], name='user_last_pwd_change_btree'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='user_username_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email'], name='user_email_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
