# Generated by Django 5.2.5 on 2025-08-22 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2100)])),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(default=44)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='catalog_bus_code_37f73c_idx'), models.Index(fields=['plate'], name='catalog_bus_plate_4c2038_idx')],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=160)),
                ('location_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='catalog_off_code_668183_idx'), models.Index(fields=['city'], name='catalog_off_city_3c2270_idx')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_destination', to='catalog.office')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_origin', to='catalog.office')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_departure_at', models.DateTimeField(db_index=True)),
                ('actual_departure_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('BOARDING', 'Boarding'), ('DEPARTED', 'Departed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12)),
                ('capacity_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='catalog.bus')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driven_departures', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='catalog.route')),
            ],
            options={
                'ordering': ['-scheduled_departure_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('scheduled_offset_min', models.IntegerField(blank=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.office')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='catalog.route')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='route_origin_destination_distinct'),
        ),
        migrations.AddIndex(
            model_name='departure',
            index=models.Index(fields=['status', 'scheduled_departure_at'], name='catalog_dep_status_44a8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='departure',
            index=models.Index(fields=['route', 'scheduled_departure_at'], name='catalog_dep_route_i_dcac3a_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['route', 'order'], name='catalog_rou_route_i_f10e23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'office'), ('route', 'order')},
        ),
    ]
