# Generated by Django 5.2.5 on 2025-08-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='office',
            name='catalog_off_city_3c2270_idx',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='city',
            new_name='department',
        ),
        migrations.AddField(
            model_name='office',
            name='locality',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='office',
            name='municipality',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='office',
            name='province',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['department'], name='catalog_off_departm_fa686b_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['province'], name='catalog_off_provinc_a7c513_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['municipality'], name='catalog_off_municip_2b74d3_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['locality'], name='catalog_off_localit_3231e5_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['active'], name='catalog_off_active_3077cd_idx'),
        ),
    ]
