# Generated by Django 5.2.5 on 2025-08-23 10:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_office_catalog_off_city_3c2270_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: usar DepartureCrew.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driven_departures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=160)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crew/photos/')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='catalog_cre_code_0284d6_idx'), models.Index(fields=['national_id'], name='catalog_cre_nationa_4f9e10_idx'), models.Index(fields=['active'], name='catalog_cre_active_2b1d86_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepartureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DRIVER', 'Driver'), ('ASSISTANT', 'Assistant')], max_length=10)),
                ('slot', models.PositiveSmallIntegerField(help_text='1 o 2. Máximo 2 asignaciones por rol y departure.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_assignments', to='catalog.crewmember')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='catalog.departure')),
            ],
            options={
                'ordering': ['departure', 'role', 'slot', 'crew_member__code'],
                'indexes': [models.Index(fields=['departure', 'role', 'slot'], name='catalog_dep_departu_afed79_idx'), models.Index(fields=['crew_member', 'role'], name='catalog_dep_crew_me_02d809_idx')],
                'unique_together': {('departure', 'crew_member'), ('departure', 'role', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='licenses/front/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='licenses/back/')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='catalog.crewmember')),
            ],
            options={
                'ordering': ['-active', '-expires_at', 'number'],
                'indexes': [models.Index(fields=['crew_member', 'number'], name='catalog_dri_crew_me_ff6298_idx'), models.Index(fields=['active'], name='catalog_dri_active_4db437_idx')],
                'unique_together': {('crew_member', 'number')},
            },
        ),
    ]
