# Generated by Django 5.2.5 on 2025-08-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_departure_driver_crewmember_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='crewmember',
            name='catalog_cre_nationa_4f9e10_idx',
        ),
        migrations.AddField(
            model_name='crewmember',
            name='role',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('ASSISTANT', 'Assistant')], db_index=True, default='ASSISTANT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='crewmember',
            index=models.Index(fields=['role'], name='catalog_cre_role_64f9a2_idx'),
        ),
    ]
