# Generated by Django 5.2.5 on 2025-08-23 17:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_crewmember_catalog_cre_nationa_4f9e10_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
