# Generated by Django 5.2.5 on 2025-08-23 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_crewmember_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewmember',
            name='notes',
        ),
        migrations.AddField(
            model_name='crewmember',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crew_members', to='catalog.office'),
        ),
        migrations.AddIndex(
            model_name='crewmember',
            index=models.Index(fields=['office'], name='catalog_cre_office__1532da_idx'),
        ),
    ]
