# Generated by Django 5.2.5 on 2025-08-23 20:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_crewmember_notes_crewmember_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='back_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='back_image'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='front_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='front_image'),
        ),
    ]
