# Generated by Django 5.2.5 on 2025-08-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_catalog_cursors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'order'), name='uix_routestop_route_order'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'office'), name='uix_routestop_route_office'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='chk_routestop_order_ge_0'),
        ),
    ]
