# Generated by Django 5.2.5 on 2025-08-28 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_routestop_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: usar DepartureAssignment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driven_departures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='departure',
            index=models.Index(fields=['bus', 'scheduled_departure_at'], name='catalog_dep_bus_id_b378a9_idx'),
        ),
    ]
