# Generated by Django 5.2.5 on 2025-08-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_catalog_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Número visible del asiento')),
                ('deck', models.PositiveSmallIntegerField(default=1, help_text='Piso: 1 o 2')),
                ('row', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('col', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('NORMAL', 'Normal'), ('SEMI_CAMA', 'Semi-cama'), ('CAMA', 'Cama'), ('LEITO', 'Leito'), ('ESPECIAL', 'Especial')], default='NORMAL', max_length=20)),
                ('is_accessible', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=160)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='catalog.bus')),
            ],
            options={
                'ordering': ['bus', 'deck', 'number'],
                'indexes': [models.Index(fields=['bus', 'deck'], name='catalog_sea_bus_id_adbdff_idx'), models.Index(fields=['bus', 'kind'], name='catalog_sea_bus_id_384824_idx'), models.Index(fields=['active'], name='catalog_sea_active_3f1a39_idx')],
                'unique_together': {('bus', 'deck', 'row', 'col'), ('bus', 'number')},
            },
        ),
    ]
