# Generated by Django 5.2.5 on 2025-08-28 20:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='photo1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo1'),
        ),
        migrations.AddField(
            model_name='bus',
            name='photo2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo2'),
        ),
        migrations.AddField(
            model_name='bus',
            name='photo3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo3'),
        ),
        migrations.AddField(
            model_name='bus',
            name='photo4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo4'),
        ),
    ]
