# catalog/management/commands/seed_offices.py
from django.core.management.base import BaseCommand
from django.db import transaction
from catalog.models import Office

SEED_OFFICES = [
    # --- SANTA CRUZ ---
    {
        "code": "SCZ-01",
        "name": "Santa Cruz Terminal Bimodal",
        "department": "Santa Cruz",
        "province": "",
        "municipality": "Santa Cruz de la Sierra",
        "locality": "Bimodal",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "SCZ-02",
        "name": "Montero Central",
        "department": "Santa Cruz",
        "province": "",
        "municipality": "Montero",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "SCZ-03",
        "name": "Warnes",
        "department": "Santa Cruz",
        "province": "",
        "municipality": "Warnes",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "SCZ-04",
        "name": "La Guardia",
        "department": "Santa Cruz",
        "province": "",
        "municipality": "La Guardia",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "SCZ-05",
        "name": "Cotoca",
        "department": "Santa Cruz",
        "province": "",
        "municipality": "Cotoca",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },

    # --- COCHABAMBA ---
    {
        "code": "CBB-01",
        "name": "Cochabamba Terminal",
        "department": "Cochabamba",
        "province": "",
        "municipality": "Cochabamba",
        "locality": "Terminal de Buses",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    # Intermedias SCZ–CBB (del enunciado del PDF)
    {
        "code": "CBB-02",
        "name": "Bulo Bulo",
        "department": "Cochabamba",
        "province": "",
        "municipality": "Entre Ríos",
        "locality": "Bulo Bulo",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "CBB-03",
        "name": "Ivirgarzama",
        "department": "Cochabamba",
        "province": "",
        "municipality": "Puerto Villarroel",
        "locality": "Ivirgarzama",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "CBB-04",
        "name": "Chimoré",
        "department": "Cochabamba",
        "province": "",
        "municipality": "Chimoré",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "CBB-05",
        "name": "Shinahota",
        "department": "Cochabamba",
        "province": "",
        "municipality": "Shinahota",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "CBB-06",
        "name": "Villa Tunari",
        "department": "Cochabamba",
        "province": "",
        "municipality": "Villa Tunari",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },

    # --- LA PAZ ---
    {
        "code": "LPZ-01",
        "name": "La Paz Central",
        "department": "La Paz",
        "province": "",
        "municipality": "La Paz",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "LPZ-02",
        "name": "El Alto Terminal",
        "department": "La Paz",
        "province": "",
        "municipality": "El Alto",
        "locality": "Terminal",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "LPZ-03",
        "name": "Viacha",
        "department": "La Paz",
        "province": "",
        "municipality": "Viacha",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "LPZ-04",
        "name": "Patacamaya",
        "department": "La Paz",
        "province": "",
        "municipality": "Patacamaya",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },

    # --- ORURO ---
    {
        "code": "ORU-01",
        "name": "Oruro Central",
        "department": "Oruro",
        "province": "",
        "municipality": "Oruro",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "ORU-02",
        "name": "Caracollo",
        "department": "Oruro",
        "province": "",
        "municipality": "Caracollo",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "ORU-03",
        "name": "Huanuni",
        "department": "Oruro",
        "province": "",
        "municipality": "Huanuni",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "ORU-04",
        "name": "Challapata",
        "department": "Oruro",
        "province": "",
        "municipality": "Challapata",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },

    # --- POTOSÍ ---
    {
        "code": "PTS-01",
        "name": "Potosí Central",
        "department": "Potosí",
        "province": "",
        "municipality": "Potosí",
        "locality": "Centro",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "PTS-02",
        "name": "Uyuni",
        "department": "Potosí",
        "province": "",
        "municipality": "Uyuni",
        "locality": "Terminal",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "PTS-03",
        "name": "Tupiza",
        "department": "Potosí",
        "province": "",
        "municipality": "Tupiza",
        "locality": "Terminal",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "PTS-04",
        "name": "Villazón",
        "department": "Potosí",
        "province": "",
        "municipality": "Villazón",
        "locality": "Terminal",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },

    # --- TARIJA ---
    {
        "code": "TRJ-01",
        "name": "Tarija Central",
        "department": "Tarija",
        "province": "",
        "municipality": "Tarija",
        "locality": "Terminal",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "TRJ-02",
        "name": "Yacuiba",
        "department": "Tarija",
        "province": "",
        "municipality": "Yacuiba",
        "locality": "Terminal",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
    {
        "code": "TRJ-03",
        "name": "Bermejo",
        "department": "Tarija",
        "province": "",
        "municipality": "Bermejo",
        "locality": "Terminal",
        "address": "",
        "phone": "",
        "location_url": "",
        "active": True,
    },
]


class Command(BaseCommand):
    help = "Crea oficinas iniciales (múltiples departamentos y puntos intermedios para tramos)"

    @transaction.atomic
    def handle(self, *args, **options):
        created_count = 0
        for data in SEED_OFFICES:
            office, created = Office.objects.get_or_create(
                code=data["code"],
                defaults={
                    "name": data["name"],
                    "department": data["department"],
                    "province": data["province"],
                    "municipality": data["municipality"],
                    "locality": data["locality"],
                    "address": data["address"],
                    "phone": data["phone"],
                    "location_url": data["location_url"],
                    "active": data["active"],
                },
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f"✓ Oficina creada: {office.code} — {office.name}"))
            else:
                self.stdout.write(f"• Oficina ya existía: {office.code}")

        self.stdout.write(self.style.SUCCESS(f"Oficinas listas ✅ (nuevas: {created_count}, total catálogo: {Office.objects.count()})"))
