# Generated by Django 5.2.5 on 2025-08-28 23:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0014_bus_photo1_bus_photo2_bus_photo3_bus_photo4'),
        ('passenger', '0003_remove_passenger_ix_passenger_nombres_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RESERVED', 'Reservado'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado'), ('NO_SHOW', 'No se presentó')], default='RESERVED', max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.departure')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_destination', to='catalog.office')),
                ('office_sold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_sold', to='catalog.office')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_origin', to='catalog.office')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='passenger.passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.seat')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_sold_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['departure', 'seat'], name='sales_ticke_departu_eb062d_idx'), models.Index(fields=['status'], name='sales_ticke_status_ce088c_idx'), models.Index(fields=['departure', 'origin', 'destination'], name='sales_ticke_departu_49277d_idx')],
                'unique_together': {('departure', 'seat', 'origin', 'destination')},
            },
        ),
    ]
