# Generated by Django 5.2.5 on 2025-08-29 19:01

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_bus_photo1_bus_photo2_bus_photo3_bus_photo4'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='sales_payme_code_f70cd7_idx'), models.Index(fields=['active'], name='sales_payme_active_c49960_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BOB', max_length=8)),
                ('transaction_id', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('FAILED', 'Fallido'), ('PARTIALLY_REFUNDED', 'Parcialmente devuelto'), ('REFUNDED', 'Devuelto')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_taken', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='catalog.office')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.ticket')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.paymentmethod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BOB', max_length=8)),
                ('status', models.CharField(choices=[('ISSUED', 'Emitido'), ('VOID', 'Anulado')], default='ISSUED', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=160)),
                ('receipt_pdf', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='receipt_pdf')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_issued', to=settings.AUTH_USER_MODEL)),
                ('issuer_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='catalog.office')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='sales.payment')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BOB', max_length=8)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('FAILED', 'Fallida')], default='PENDING', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund_pdf', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='refund_pdf')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ticket', 'status'], name='sales_payme_ticket__876e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='sales_payme_method__267df3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='sales_payme_created_0df64f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['number'], name='sales_recei_number_c94600_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status'], name='sales_recei_status_fe434f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['issued_at'], name='sales_recei_issued__cf5c85_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='sales_refun_payment_59cbad_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['created_at'], name='sales_refun_created_ad8685_idx'),
        ),
    ]
